version: '3'

networks:
  monreseau:
    external: false

services:
  web:
    build: .
    container_name: contweb
    volumes:
      - monsitestatics:/code/static/
    ports:
      - '8000:8000'
    depends_on:
      - db
      - db_mysql
    environment:
      DBToUse: "PostgreSQL"  # "MySQL" ou "PostgreSQL"
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      MYSQL_DATABASE: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_HOST: db_mysql
      MYSQL_PORT: 3306
    networks:
      - monreseau

  db:
    image: postgres:13-alpine
    container_name: post
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - monreseau

  db_mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_DATABASE: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - monreseau

  nginx:
    image: 'nginx:1.19-alpine'
    container_name: contnginx
    volumes:
      - ./static:/home/app/web/static_assets
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - monreseau
    ports:
      - '80:80'

volumes:
  monsitestatics:
  postgres_data:
  mysql_data:
