version: '3.8'

services:
  client:
    container_name: client
    build:
      context: .
      dockerfile: init_app
    ports:
      - "8000:8000"
  
  api:
    container_name: api

  database1:
    container_name: database1
    build:
      context: .
      dockerfile: ../processors/keras/Dockerfile
    ports:
      - "8050:8050"

  database2:
    container_name: database2
    build:
      context: .
      dockerfile: init_db2
    ports:
      - "5432:8050"
    environment:
      - ENV=
      - 

  proxy:
    build:
      context: .
      dockerfile: API/dockerfile_nginx
    container_name: proxy
      
volumes:
  data:

